module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    theme: {
        extend: {
            colors: {
                DarkBack: '#000209',
                Primary: '#8B48FE',
                FaqHeading: '#202C33',
                FaqBody: '#949494',
                HomeCardHeading: '#32A9D1',
                Secondary: '#66FCF3',
                Gray: '#C2CFF3',
                TextPassageLight: '#E7E7E7',
                TextPassageDark: '#2D3131',
                ButtonBg: '#00B1B1',
                TextDarkBlue: '#01DFB8',
                SponsorCard: '#E8E7D9',
                TextSchedule: '#BBE8E6',
                TrackBack: '#F9F9F9',
                CardBack: '#FFF',
                DarkButtonText: '#2D3131',
            },
            screens: {
                screen6: { max: '950px' },
                screen1: { max: '800px' },
                screen8: { max: '770px' },
                screen2: { max: '720px' },
                screen3: { max: '680px' },
                screen7: { max: '610px' },
                screen4: { max: '580px' },
                screen5: { max: '480px' },
            },
            width: {
                sponsor1: '175px',
                sponsor2: '330px',
                sponsor3: '320px',
                sponsor4: '320px',
                sponsor5: '400px',
                sponsor6: '330px',
                sponsor7: '360px',
                sponsor1_1: '150px',
                sponsor2_1: '280px',
                sponsor3_1: '275px',
                sponsor4_1: '275px',
                sponsor5_1: '345px',
                sponsor6_1: '280px',
                sponsor7_1: '305px',
                schedule1: '555px',
                schedule1_1: '360px',
            },
            backgroundImage: {
                backgroundHeroImage: "url('/src/assets/img/bgHero.svg')",
                backgroundHomeCard: "url('/src/assets/img/HomeCardBack.png')",
                backgroundHomeCard2:
                    "url('/src/assets/img/HomeCardBack_2.png')",
                backgroundHomeFAQ: "url('/src/assets/img/HomeFaqBack.png')",
                backgroundEvent_1: "url('/src/assets/img/back_event_1.png')",
                backgroundTeam_1: "url('/src/assets/img/back_team_1.png')",
                backgroundPrize_1: "url('/src/assets/img/back_prize_1.png')",
                backgroundPrize_2: "url('/src/assets/img/back_prize_2.png')",
                backgroundSpeaker_1:
                    "url('/src/assets/img/back_speaker_1.png')",
                backgroundSpeaker_2:
                    "url('/src/assets/img/back_speaker_2.png')",
                backgroundSpeaker_3:
                    "url('/src/assets/img/back_speaker_3.png')",
                backgroundHome: "url('/src/assets/img/background.png')",
            },
        },
    },
    plugins: [],
}
