module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    theme: {
        extend: {
            colors: {
                DarkBack: '#000209',
                Primary: '#202833',
                FaqHeading: '#202C33',
                FaqBody: '#949494',
                Secondary: '#66FCF3',
                Gray: '#C2CFF3',
                TextPassage: '#949494',
                ButtonBg: '#00B1B1',
                TextDarkBlue: '#46A29F',
                SponsorCard: '#E8E7D9',
                TextSchedule: '#BBE8E6',
                TrackBack: '#E8FFFE',
                CardBack: '#FFF',
            },
            screens: {
                screen6: { max: '950px' },
                screen1: { max: '800px' },
                screen8: { max: '770px' },
                screen2: { max: '720px' },
                screen3: { max: '680px' },
                screen7: { max: '610px' },
                screen4: { max: '580px' },
                screen5: { max: '480px' },
            },
            width: {
                sponsor1: '250px',
                sponsor2: '330px',
                sponsor3: '320px',
                sponsor4: '320px',
                sponsor5: '400px',
                sponsor6: '330px',
                sponsor7: '360px',
                sponsor1_1: '210px',
                sponsor2_1: '280px',
                sponsor3_1: '275px',
                sponsor4_1: '275px',
                sponsor5_1: '345px',
                sponsor6_1: '280px',
                sponsor7_1: '305px',
                schedule1: '555px',
                schedule1_1: '360px',
            },
            backgroundImage: {
                backgroundHeroImage: "url('/src/assets/img/bgHero.svg')",
            },
        },
    },
    plugins: [],
}
